name: ManthanKeim

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: Bull-s-Eye@master
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
